apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200

    jsonData:
      httpMethod: GET
      defaultQueryType: search
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Throughput'
            query: 'sum(rate(apm_calls_total{$$__tags}[$$__rate_interval]))'
          - name: 'Latency (p95)'
            query: 'histogram_quantile(0.95, sum(rate(apm_duration_milliseconds_bucket{$$__tags}[$$__rate_interval])) by (le))'
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      nodeGraph:
        enabled: true


