"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=mid9l1&iopk75_zjtphqw75&61wzcb9ipjoq5b7y(6@f(+y+n"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = ["http://localhost:8001", "http://127.0.0.1:8001"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "api.middleware.UserAgentMiddleware",
    "api.middleware.DeviceBindingMiddleware",
    "api.middleware.TenantStorageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "api.middleware.RequestLoggingMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DJANGO_DB_NAME", "django_otel"),
        "USER": os.environ.get("DJANGO_DB_USER", "django"),
        "PASSWORD": os.environ.get("DJANGO_DB_PASSWORD", "django"),
        "HOST": os.environ.get("DJANGO_DB_HOST", "localhost"),
        "PORT": int(os.environ.get("DJANGO_DB_PORT", "5433")),
        "CONN_MAX_AGE": 600,
        "CONN_HEALTH_CHECKS": True,
    },
    "slave1": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("SLAVE1_DB_NAME", "django_otel_slave1"),
        "USER": os.environ.get("SLAVE1_DB_USER", "django"),
        "PASSWORD": os.environ.get("SLAVE1_DB_PASSWORD", "django"),
        "HOST": os.environ.get("SLAVE1_DB_HOST", "localhost"),
        "PORT": int(os.environ.get("SLAVE1_DB_PORT", "5434")),
        "CONN_MAX_AGE": 600,
        "CONN_HEALTH_CHECKS": True,
    },
    "slave2": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("SLAVE2_DB_NAME", "django_otel_slave2"),
        "USER": os.environ.get("SLAVE2_DB_USER", "django"),
        "PASSWORD": os.environ.get("SLAVE2_DB_PASSWORD", "django"),
        "HOST": os.environ.get("SLAVE2_DB_HOST", "localhost"),
        "PORT": int(os.environ.get("SLAVE2_DB_PORT", "5435")),
        "CONN_MAX_AGE": 600,
        "CONN_HEALTH_CHECKS": True,
    },
    "slave3": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("SLAVE3_DB_NAME", "django_otel_slave3"),
        "USER": os.environ.get("SLAVE3_DB_USER", "django"),
        "PASSWORD": os.environ.get("SLAVE3_DB_PASSWORD", "django"),
        "HOST": os.environ.get("SLAVE3_DB_HOST", "localhost"),
        "PORT": int(os.environ.get("SLAVE3_DB_PORT", "5436")),
        "CONN_MAX_AGE": 600,
        "CONN_HEALTH_CHECKS": True,
    },
}

EXTERNAL_API_URL = os.environ.get("EXTERNAL_API_URL", "http://localhost:8080/get")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("DJANGO_REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/minute",
        "user": "1000/minute",
        "burst_test": "5/minute",
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "api.middleware": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

# tp_trace OpenTelemetry bootstrap (fail-safe; no-op when SDK absent)
from config.otel import setup_telemetry

setup_telemetry()
